[platformio]
default_envs = cc2510f32-smoke

[env:cc2510f32-smoke]
platform = platformio/intel_mcs51@2.2.0
platform_packages = platformio/toolchain-sdcc@1.40400.0
board = cc2510f32
extra_scripts = pre:configure.py
upload_protocol = custom
upload_command = echo Upload is not configured
build_flags = --model-small
