[env:cardputer-adv]
extends = esp32
board = m5stack-stamps3
build_flags =
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DETAG_CARDPUTER_ADV=1
lib_deps =
    m5stack/M5GFX@0.2.28
    m5stack/M5Unified@0.2.21
    z3t0/IRremote@4.4.1
    https://github.com/m5stack/M5Cardputer.git#2d4fa6646e4e5b47e0af96214b003aa7b15b8d81

[env:esp32-devkit]
extends = esp32
board = esp32dev

[env:esp32-s3-devkit]
extends = esp32
board = esp32-s3-devkitc-1
build_flags =
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
